apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-npu-artifacts
  namespace: failure-prediction
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
